CREATE TABLE quantity_measurement(

id INT AUTO_INCREMENT PRIMARY KEY,
operation VARCHAR(50),
type VARCHAR(50),
value1 DOUBLE,
value2 DOUBLE,
result DOUBLE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);