server.port=${PORT:8081}
spring.application.name=auth-service

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP:false}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:${HOSTNAME:localhost}}
eureka.instance.non-secure-port=${PORT:8081}
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}:${eureka.instance.non-secure-port}

jwt.secret=${JWT_SECRET}
app.oauth2.redirect-url=${FRONTEND_OAUTH_SUCCESS_URL:http://localhost:5173/oauth-success}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
spring.security.oauth2.client.registration.google.client-name=Google