# ========================
# SERVER CONFIG
# ========================
server.port=${SERVER_PORT:8083}
spring.application.name=history-service


# ========================
# DATABASE CONFIG
# ========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# JPA settings
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}


# ========================
# EUREKA CONFIG
# ========================
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}


# ========================
# JWT CONFIG
# ========================
jwt.secret=${JWT_SECRET}

spring.profiles.active=local